import { ActivityCategory } from '../../common/schemas/activity-category';

export const activityCategoriesMock: ActivityCategory[] = [
  {
    id: '1',
    name: 'Running',
    status: 'ACTIVE',
    icon: 'person-running',
    description: undefined,
    goalValue: 3,
    goalType: 'MIN',
    repeatType: 'DAILY',
    unit: 'km',
    createdDate: '2022-01-01',
    validFrom: '2022-01-01',
    validTo: '2022-12-31',
  },
  {
    id: '2',
    name: 'Listening to music',
    status: 'ACTIVE',
    icon: 'music',
    description: undefined,
    goalValue: 1,
    goalType: 'MIN',
    repeatType: 'DAILY',
    unit: 'piece',
    createdDate: '2022-01-01',
    validFrom: '2022-01-01',
    validTo: '2022-12-31',
  },
  {
    id: '3',
    name: 'Meetings',
    status: 'ACTIVE',
    icon: 'handshake',
    description: undefined,
    goalValue: 120,
    goalType: 'MAX',
    repeatType: 'DAILY',
    unit: 'minutes',
    createdDate: '2022-01-01',
    validFrom: '2022-01-01',
    validTo: '2022-12-31',
  },
  {
    id: '4',
    name: 'Swimming',
    status: 'ACTIVE',
    icon: 'person-drowning',
    description: undefined,
    goalValue: 120,
    goalType: 'MAX',
    repeatType: 'DAILY',
    unit: 'minutes',
    createdDate: '2022-01-01',
    validFrom: '2022-01-01',
    validTo: '2022-12-31',
  },
  {
    id: '5',
    name: 'Dev',
    status: 'ACTIVE',
    icon: 'code',
    description: undefined,
    goalValue: 120,
    goalType: 'MAX',
    repeatType: 'DAILY',
    unit: 'minutes',
    createdDate: '2022-01-01',
    validFrom: '2022-01-01',
    validTo: '2022-12-31',
  },
];
