import Head from 'next/head';
import Link from '../common/components/Link/Link';
// import style from './Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Habitea</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello world</h1>
        <Link href="/login">Login</Link>
      </main>
    </div>
  );
}
