import Head from 'next/head';
import Image from 'next/image';
import classNames from 'classnames';
import styles from './Home.module.scss';
import heroBgImg from '../public/backgrounds/bg-main.jpg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Habitea</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.hero}>
        <Image
          className={styles['background-image']}
          src={heroBgImg}
          alt={'background image'}
          placeholder="blur"
          fill
        ></Image>
        <div className={styles.hello}>
          <h1 className={classNames(styles.title)}>Habitea</h1>
          <h2 className={classNames(styles.emph, styles.subtitle)}>
            Get in control of your habits
          </h2>
          <span className={styles.quote}>
            “Until you make the unconscious conscious, it will direct your life
            and you will call it fate.”
          </span>
          <button className={classNames(styles.cta)} color="default">
            <strong>Get started</strong>
          </button>
        </div>
      </div>
    </>
  );
}
